const CARDS = [
  {
    id: 1,
    value: '#d958a2',
    isMatch: false,
    isOpen: false
  }, {
    id: 2,
    value: '#d366e4',
    isMatch: false,
    isOpen: false
  }, {
    id: 3,
    value: '#84e458',
    isMatch: false,
    isOpen: false
  }, {
    id: 4,
    value: '#5873e4',
    isMatch: false,
    isOpen: false
  }, {
    id: 5,
    value: '#468489',
    isMatch: false,
    isOpen: false
  }, {
    id: 6,
    value: '#ea8645',
    isMatch: false,
    isOpen: false
  }, {
    id: 7,
    value: '#daf04a',
    isMatch: false,
    isOpen: false
  }, {
    id: 8,
    value: '#b60000',
    isMatch: false,
    isOpen: false
  }, {
    id: 9,
    value: '#daf04a',
    isMatch: false,
    isOpen: false
  }, {
    id: 10,
    value: '#b60000',
    isMatch: false,
    isOpen: false
  }, {
    id: 11,
    value: '#d958a2',
    isMatch: false,
    isOpen: false
  }, {
    id: 12,
    value: '#d366e4',
    isMatch: false,
    isOpen: false
  }, {
    id: 13,
    value: '#84e458',
    isMatch: false,
    isOpen: false
  }, {
    id: 14,
    value: '#5873e4',
    isMatch: false,
    isOpen: false
  }, {
    id: 15,
    value: '#468489',
    isMatch: false,
    isOpen: false
  }, {
    id: 16,
    value: '#ea8645',
    isMatch: false,
    isOpen: false
  },
]

 export default CARDS